### ISSUE TITLE
overriding post forgot password doesn't work

### ISSUE THREAD

**Issue by anis-brahmi** [coopTilleuls/CoopTilleulsForgotPasswordBundle#114] opened 2022-12-16 13:56 UTC
Hello,
I'm trying to override post forgot password but its doesn't work for me.
i created my own controller to make my logic.

coop_tilleuls_forgot_password.update:
  path: /forgot-password/{tokenValue}
  methods: [ POST ]
  defaults:
    _controller: App\Controller\Action\UpdateResetPasswordActionController
    
 --Error: 
       There is no extension able to load the configuration for "coop_tilleuls_forgot_password.update" (in "/var/www/html/config/packages/coop_tilleuls_forgot_password.yaml"). Looked for namespace "coop_tilleuls_forgot_password.up  
    date", found ""framework", "doctrine", "doctrine_migrations", "debug", "twig", "web_profiler", "twig_extra", "security", "monolog", "maker", "sensio_framework_extra", "doctrine_fixtures", "nelmio_api_doc", "nelmio_alice", "  
    fidry_alice_data_fixtures", "hautelook_alice", "nelmio_cors", "api_platform", "lexik_jwt_authentication", "vich_uploader", "coop_tilleuls_forgot_password"" in /var/www/html/config/packages/coop_tilleuls_forgot_password.yaml  
     (which is being imported from "/var/www/html/src/Kernel.php").
     
Please help me

**Comment by vincentchalamon** [comment] 2022-12-16 13:58
Hello,

It seems you're trying to load a route in a package. You should move this custom configuration in `config/routes` directory.

Closing as this is not a bug in this bundle.

**Closed by vincentchalamon** 2022-12-16 13:58 UTC
